name: Maven Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B verify --file pom.xml

    - name: Get Allure history
      uses: actions/checkout@v3
      if: steps.test.outcome == 'success'
      continue-on-error: true
      with:
        ref: allure-pages
        path: allure-pages

    - name: Allure Report
      uses: simple-elf/allure-report-action@master
      if: steps.test.outcome == 'success'
      id: allure-report
      with:
        allure_results: target/allure-results
        gh_pages: allure-pages
        allure_report: target/allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: steps.test.outcome == 'success'
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: allure-pages
        PUBLISH_DIR: allure-history

    - name: Upload Allure artifacts
      uses: actions/upload-artifact@v3
      if: steps.test.outcome == 'success'
      with:
        name: allure-report
        path: target/allure-report/
        retention-days: 30

    - name: Test Summary
      if: steps.test.outcome == 'success'
      uses: test-summary/action@v2
      with:
        paths: "target/failsafe-reports/failsafe-summary.xml"

    - name: Test Report Summary
      if: steps.test.outcome == 'success'
      run: |
        echo "[Click here to open Allure Report!!!](https://leonardust.github.io/serenity-bdd-restassured-starter/)" >> $GITHUB_STEP_SUMMARY    



